---
title: "Final Project"
author: "Team 4"
date: "4/2/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
#knitr::opts_knit$set(root.dir = "/cloud/project")
knitr::opts_knit$set(root.dir = "C:/Users/jsmit/Desktop/WSU/Data Analytics/CPTS 424/Final Report")
```

```{r read_time_data, warning=FALSE}
suppressMessages(library(tidyverse))
suppressMessages(library(readxl))
travel_times <- "Data/I-405_Travel_Times_-_PDR.xlsx"
#Map all the sheets in the file to a dataframe
data = suppressMessages(travel_times %>% excel_sheets() %>% set_names() %>% map(read_excel, path=travel_times))
```

```{r clean_time_data, warning = FALSE}
#maps all the data into the global environment
s = list2env(data, envir = .GlobalEnv)
#Changing table names for functionality
NBR = `NB Rates`
SBR = `SB Rates`
# Change columns names 
NBR <-select(NBR,starts_with("D")) %>% select_all(~str_replace(., "Displayed Toll Rate for +", ""))
SBR <-select(SBR,starts_with("D")) %>% select_all(~str_replace(., "Displayed Toll Rate for +", ""))
#Converting toll terminology to numerical data
NBR[NBR=="OPEN"] <- 0
NBR[NBR=="CLOSED"] <- 0
NBR[NBR=="FREE"] <- 0
NBR[NBR=="HOV ONLY"] <- 0
SBR[SBR=="OPEN"] <- 0
SBR[SBR=="FREE"] <- 0
SBR[SBR=="HOV ONLY"] <- 0
SBR[SBR=="CLOSED"] <- 0
# Adding time column 
NBR <- add_column(NBR,Time = `NB Rates`$Time,.before = 1)
SBR <- add_column(SBR,Time = `SB Rates`$Time,.before = 1)
# Removing columns with no data in them at all
NBR<- NBR %>% select_if(~ !all(is.na(.)))
SBR<- SBR %>% select_if(~ !all(is.na(.)))
```


```{r TT_fix_time_columns, warning= FALSE}
#convert POSIXct to character, strip the date and time zone
TOTALGN$`15.06 miles` <- as.character(TOTALGN$`15.06 miles`, "%H:%M:%S") 
TOTALHN$`15.06 miles` <- as.character(TOTALGN$`15.06 miles`, "%H:%M:%S")
TOTALGS$`15.06 miles` <- as.character(TOTALGN$`15.06 miles`, "%H:%M:%S")
TOTALHS$`15.06 miles` <- as.character(TOTALGN$`15.06 miles`, "%H:%M:%S")

#convert character to time
suppressMessages(library(chron))
TOTALGN$`15.06 miles` <- chron(times = TOTALGN$`15.06 miles`)
TOTALHN$`15.06 miles` <- chron(times = TOTALHN$`15.06 miles`)
TOTALGS$`15.06 miles` <- chron(times = TOTALGS$`15.06 miles`)
TOTALHS$`15.06 miles` <- chron(times = TOTALHS$`15.06 miles`)

#rename the columns
names(TOTALGN)[1] <-"Time"
names(TOTALHN)[1] <-"Time"
names(TOTALGS)[1] <-"Time"
names(TOTALHS)[1] <-"Time"
```
  
```{r convert_data, warning = FALSE}
#converts toll rates into numeric data without the time column being affected
NBR <- NBR %>% mutate_if(is.character, as.numeric,na.rm=TRUE)
SBR <- SBR %>% mutate_if(is.character, as.numeric,na.rm=TRUE)
#Fix time column
NBR$Time <- as.character(NBR$Time, "%H:%M:%S") 
SBR$Time <- as.character(SBR$Time, "%H:%M:%S") 
library(chron)
NBR$Time <- chron(times = NBR$Time)
SBR$Time <- chron(times = SBR$Time)

```

```{r looking_at_columns_with_missing_values}
#info on missing values:
#https://www.wsdot.wa.gov/Tolling/405/rates.htm
#column wise missing values
na_countNBR <-sapply(NBR, function(y) sum(length(which(is.na(y)))))
na_countSBR <-sapply(SBR, function(y) sum(length(which(is.na(y)))))
#Remove columns that have any missing data
NBR<- NBR %>% select_if(~ !any(is.na(.)))
SBR<- SBR %>% select_if(~ !any(is.na(.)))
```

```{r read_volume_data, warning = FALSE}
volume <- read.csv("Data/I-405_Volumes_-_PDR.csv", header=TRUE,  stringsAsFactors = FALSE)
```

```{r vol_remove_col}
#remove unneccesary second row
volume <- volume[-c(1),]
```

```{r vol_convert_header}
	
North <- volume[,0:11]
South <- volume[,12:19]
time_date <- volume[,0:3]
South <- cbind(time_date, South)
North[,"direction"] <- "North"
South[,"direction"] <- "South"
```

```{r vol_format_south}
s1 <- cbind(South[,0:5], South[,12:12]) #combine date/time data, volume data for first mileage post, and direction data
s1[,"Mileage"] <- s1[1,4] #create column to label milage post
s1 <- s1[-c(1),] #remove initial label column 

s2 <- cbind(time_date,South[,6:7],South[,12:12])
s2[,"Mileage"] <- s2[1,4]
s2 <- s2[-c(1),]

s3 <- cbind(time_date, South[,8:9],South[,12:12])
s3[,"Mileage"] <- s3[1,4]
s3 <- s3[-c(1),]

s4 <- cbind(time_date, South[,10:11],South[,12:12])
s4[,"Mileage"] <- s4[1,4]
s4 <- s4[-c(1),]

```

```{r vol_format_north}
n1 <- cbind(North[,0:5], North[,12:12])
n1[,"Mileage"] <- n1[1,4]
n1 <- n1[-c(1),]

n2 <- cbind(time_date,North[,6:7],North[,12:12])
n2[,"Mileage"] <- n2[1,4]
n2 <- n2[-c(1),]

n3 <- cbind(time_date, North[,8:9],North[,12:12])
n3[,"Mileage"] <- n3[1,4]
n3 <- n3[-c(1),]

n4 <- cbind(time_date, North[,10:11],North[,12:12])
n4[,"Mileage"] <- n4[1,4]
n4 <- n4[-c(1),]

```

```{r vol_southbound_lanes}
lists=list(s1, s2, s3, s4)
south_data <- data.frame()
for (x in lists){
  df <- x
  temp <- grepl("H", df[1,4], fixed=TRUE)
  temp1 <- grepl("H", df[1,5],  fixed=TRUE)
  if (temp==TRUE & temp1==FALSE){
    colnames(df) = c("Date", "Day_of_Week", "Time", "T_Volume", "G_Volume", "Direction", "Mile_Post")
  }
  else{
   colnames(df) = c("Date", "Day_of_Week", "Time", "G_Volume", "T_Volume", "Direction", "Mile_Post")
   }
  df <- df[-c(1),]
  south_data <- rbind(south_data,df)
}

```

```{r vol_northbound_lanes}
lists=list(n1, n2, n3, n4)
north_data <- data.frame()
for (x in lists){
  df <- x
  temp <- grepl("H", df[1,4], fixed=TRUE)
  temp1 <- grepl("H", df[1,5],  fixed=TRUE)
  if (temp==TRUE & temp1==FALSE){
    colnames(df) = c("Date", "Day_of_Week", "Time", "T_Volume", "G_Volume", "Direction", "Mile_Post")
  }
  else{
   colnames(df) = c("Date", "Day_of_Week", "Time", "G_Volume", "T_Volume", "Direction", "Mile_Post")
   }
  df <- df[-c(1),]
  north_data <- rbind(north_data,df)
}

```

```{r vol_combine}

volume_data <- rbind(north_data,south_data)

```

```{r vol_data_convert, warning = FALSE}
#install.packages("chron")
library(chron)
volume_data$Time <- chron(times = volume_data$Time)
volume_data$Date <- as.Date(volume_data$Date, "%m/%d/%Y")
library(dplyr)
volume_data = volume_data %>% mutate(Day_of_Week = case_when(
    Day_of_Week == 1  ~ "Mon",
    Day_of_Week == 2 ~ "Tues",
    Day_of_Week == 3 ~ "Wed",
    Day_of_Week == 4 ~ "Thurs",
    Day_of_Week == 5 ~ "Fri",
    Day_of_Week == 6 ~ "Sat",
    Day_of_Week == 7 ~ "Sun"))
volume_data$T_Volume <- as.integer(volume_data$T_Volume)
volume_data$G_Volume <- as.integer(volume_data$G_Volume)
volume_data$Mileage <- as.numeric((volume_data$Mile_Post))
volume_data <- subset(volume_data, select = -c(Mile_Post))
#head(volume_data) #Commented out to avoid redundancy in the html report

```


```{r preprocessing1}
#filter out weekends,holidays, and snowstorm dates from the data
#remove weekends from volume data
newdata <- volume_data[ which(!(volume_data$Day_of_Week) %in% c('Sat','Sun')), ]
#remove Holidays from volume data
holidays <- c(as.Date("2019-01-01"), as.Date("2019-01-20"), as.Date("2019-02-17"), as.Date("2019-05-25"),as.Date("2019-07-03"), as.Date("2019-09-07"),as.Date("2019-11-11"), as.Date("2019-11-26"), as.Date("2019-12-25"))
newdata2 <- newdata[ which(!(newdata$Date) %in% holidays), ]
#remove snowstorm dates Feb 1st-Feb 15th
library(dplyr)
vol_data <- newdata2 %>% filter(newdata2$Date < "2019-02-01" | newdata2$Date > "2019-02-15" )

#get list of remaining dates for 2019
dates <- unique(vol_data$Date)

HN = TOTALHN
#filter northbound toll lane dates 
names(HN) = gsub(pattern = " \\(.*", replacement = "", x = names(HN)) 
names(HN) <- format(as.Date(names(HN), format = "%m/%d/%y"),
    format = "%Y-%m-%d")
NB_times <-HN[ , (as.Date(names(HN)) %in% dates)] 
NB_times <-cbind(HN[,1], NB_times)
row.names(NB_times) <- NB_times[,1]
NB_times[1] <- NULL

HS = TOTALHS
#filter southbound toll lane dates 
names(HS) = gsub(pattern = " \\(.*", replacement = "", x = names(HS)) 
names(HS) <- format(as.Date(names(HS), format = "%m/%d/%y"),
    format = "%Y-%m-%d")
SB_times <-HS[ , (as.Date(names(HS)) %in% dates)] 
SB_times <-cbind(HS[,1], SB_times)
row.names(SB_times) <- SB_times[,1]
SB_times[1] <- NULL

```


```{r PlotSpeedvTimeofDay, warning = FALSE, message = FALSE}

#convert seconds to hours (divide by 3600)
SB_times_hrs <- SB_times/3600
NB_times_hrs <- NB_times/3600

#Calculate speed (v=distance/time, where distance is 15.06 miles)
SB_mph <- 15.06/SB_times_hrs
NB_mph <- 15.06/NB_times_hrs

#Get the average speed for each time of day
SB <- data.frame(row.names(SB_mph), rowMeans(SB_mph))
names(SB)[1] <- "Time_of_Day"
names(SB)[2] <- "Avg_Speed"
rownames(SB) <- 1:nrow(SB)
library(chron)
SB$Time_of_Day <- chron(times=SB$Time_of_Day)

NB <- data.frame(row.names(NB_mph), rowMeans(NB_mph))
names(NB)[1] <- "Time_of_Day"
names(NB)[2] <- "Avg_Speed"
rownames(NB) <- 1:nrow(NB)
NB$Time_of_Day <- chron(times=NB$Time_of_Day)

#plot average speed by time of day
library(ggplot2)

p1 = ggplot() + geom_point(data=SB, aes(x=SB$Time_of_Day, y=SB$Avg_Speed, color='Southbound')) + geom_point(data=NB, aes(x=NB$Time_of_Day, y=NB$Avg_Speed, color='Northbound'))+  scale_x_time( name= "Time of Day", breaks = c('0', '.25', '.5', '.75', '1.0'),  labels = c("12am", "6am", "12pm", "6pm", "12am")) + ylab("Average Speed (mph)") + ggtitle("Average Speed")  +  geom_hline(yintercept = 45, color='black', linetype = 3) + scale_color_manual(values = c('Northbound' = 'darkblue','Southbound' = 'red')) +labs(color = 'Direction')

p1
```





```{r calculate_segment_speeds, message=FALSE, warning=FALSE}
library(readxl)
library(dplyr)

#Read in summary stats to get average speed for Oct-Dec 2019
NB_BtoR <- read_excel(path = "Data/NB_Bellevue_to_RoseHill.xlsx", range = "HOV TT Summary!A1:C289") 
NB_Bto522 <- read_excel(path = "Data/NB_Bellevue_to_SR522.xlsx", range = "HOV TT Summary!A1:C289")
SB_RtoB <- read_excel(path = "Data/SB_RoseHill_to_Bellevue.xlsx", range = "HOV TT Summary!A1:C289")
SB_522toB <- read_excel(path = "Data/SB_SR522_to_Bellevue.xlsx", range = "HOV TT Summary!A1:C289")
NB_148to522 <- read_excel(path = "Data/NB_148th_to_SR522.xlsx", range = "HOV TT Summary!A1:C289")
SB_522to148 <- read_excel(path = "Data/SB_SR522_to_148th.xlsx", range = "HOV TT Summary!A1:C289") 
NB_Bto527 <- read_excel(path = "Data/NB_Bellevue_to_SR527.xlsx", range = "HOV TT Summary!A1:C289")
SB_527toB <- read_excel(path = "Data/SB_SR527_to_Bellevue.xlsx", range = "HOV TT Summary!A1:C289") 

#Read in daily travel times for Oct-Dec 2019
NB_BtoR_tt <- read_excel(path = "Data/NB_Bellevue_to_RoseHill.xlsx", sheet = "HOV TravelTimes")  %>% setNames(., c('Time', format(as.Date(as.numeric(names(.)[-1]), origin = '1899-12-30'), '%Y-%m-%d')))
NB_Bto522_tt <- read_excel(path = "Data/NB_Bellevue_to_SR522.xlsx", sheet = "HOV TravelTimes")  %>% setNames(., c('Time', format(as.Date(as.numeric(names(.)[-1]), origin = '1899-12-30'), '%Y-%m-%d')))
SB_RtoB_tt <- read_excel(path = "Data/SB_RoseHill_to_Bellevue.xlsx", sheet = "HOV TravelTimes")  %>% setNames(., c('Time', format(as.Date(as.numeric(names(.)[-1]), origin = '1899-12-30'), '%Y-%m-%d')))
SB_522toB_tt <- read_excel(path = "Data/SB_SR522_to_Bellevue.xlsx", sheet = "HOV TravelTimes")  %>% setNames(., c('Time', format(as.Date(as.numeric(names(.)[-1]), origin = '1899-12-30'), '%Y-%m-%d')))
NB_148to522_tt <- read_excel(path = "Data/NB_148th_to_SR522.xlsx", sheet = "HOV TravelTimes")  %>% setNames(., c('Time', format(as.Date(as.numeric(names(.)[-1]), origin = '1899-12-30'), '%Y-%m-%d')))
SB_522to148_tt <- read_excel(path = "Data/SB_SR522_to_148th.xlsx", sheet = "HOV TravelTimes")  %>% setNames(., c('Time', format(as.Date(as.numeric(names(.)[-1]), origin = '1899-12-30'), '%Y-%m-%d')))
NB_Bto527_tt <- read_excel(path = "Data/NB_Bellevue_to_SR527.xlsx", sheet = "HOV TravelTimes")  %>% setNames(., c('Time', format(as.Date(as.numeric(names(.)[-1]), origin = '1899-12-30'), '%Y-%m-%d')))
SB_527toB_tt <- read_excel(path = "Data/SB_SR527_to_Bellevue.xlsx", sheet = "HOV TravelTimes")  %>% setNames(., c('Time', format(as.Date(as.numeric(names(.)[-1]), origin = '1899-12-30'), '%Y-%m-%d'))) 

#get dates without weekends and holidays in Oct-Dec
new_dates = dates[dates >= '2019-10-01'] 

#calculte the speed for each day and time, for each segment, eliminate holidays and weekends 
NB_BtoR_tt[,-1] =  NB_BtoR_tt[,-1] / 3600 #convert seconds to hours (seconds/3600)
NB_BtoR_dist = mean(NB_BtoR$`Avg. Speed`* (NB_BtoR$`Avg. TTS`/3600)) #distance = speed * time to get the length of the stretch
NB_BtoR_speed = NB_BtoR_dist/NB_BtoR_tt[,-1] #speed(mph) = distance(m)/time(hr)
NB_BtoR_speed[NB_BtoR_speed < 0] <- NA  #set bad data values to NA
NB_BtoR_speed <-NB_BtoR_speed[ , (as.Date(names(NB_BtoR_speed)) %in% new_dates)]


NB_Bto522_tt[,-1] =  NB_Bto522_tt[,-1] / 3600 
NB_Bto522_speed = (mean(NB_Bto522$`Avg. Speed`* (NB_Bto522$`Avg. TTS`/3600))) /NB_Bto522_tt[,-1] 
NB_Bto522_speed[NB_Bto522_speed < 0] <- NA  
NB_Bto522_speed <-NB_Bto522_speed[ , (as.Date(names(NB_Bto522_speed)) %in% new_dates)]

SB_RtoB_tt[,-1] =  SB_RtoB_tt[,-1] / 3600 
SB_RtoB_speed = (mean(SB_RtoB$`Avg. Speed`* (SB_RtoB$`Avg. TTS`/3600))) /SB_RtoB_tt[,-1] 
SB_RtoB_speed[SB_RtoB_speed < 0] <- NA 
SB_RtoB_speed <-SB_RtoB_speed[ , (as.Date(names(SB_RtoB_speed)) %in% new_dates)]

SB_522toB_tt[,-1] =  SB_522toB_tt[,-1] / 3600 
SB_522toB_speed = (mean(SB_522toB$`Avg. Speed`* (SB_522toB$`Avg. TTS`/3600))) /SB_522toB_tt[,-1] 
SB_522toB_speed[SB_522toB_speed < 0] <- NA  
SB_522toB_speed <-SB_522toB_speed[ , (as.Date(names(SB_522toB_speed)) %in% new_dates)]

NB_148to522_tt[,-1] =  NB_148to522_tt[,-1] / 3600 
NB_148to522_speed = (mean(NB_148to522$`Avg. Speed`* (NB_148to522$`Avg. TTS`/3600))) /NB_148to522_tt[,-1] 
NB_148to522_speed[NB_148to522_speed < 0] <- NA
NB_148to522_speed <-NB_148to522_speed[ , (as.Date(names(NB_148to522_speed)) %in% new_dates)]

SB_522to148_tt[,-1] =  SB_522to148_tt[,-1] / 3600 
SB_522to148_speed = (mean(SB_522to148$`Avg. Speed`* (SB_522to148$`Avg. TTS`/3600))) /SB_522to148_tt[,-1] 
SB_522to148_speed[SB_522to148_speed < 0] <- NA 
SB_522to148_speed <-SB_522to148_speed[ , (as.Date(names(SB_522to148_speed)) %in% new_dates)]

NB_Bto527_tt[,-1] =  NB_Bto527_tt[,-1] / 3600 
NB_Bto527_speed = (mean(NB_Bto527$`Avg. Speed`* (NB_Bto527$`Avg. TTS`/3600))) /NB_Bto527_tt[,-1] 
NB_Bto527_speed[NB_Bto527_speed < 0] <- NA 
NB_Bto527_speed <-NB_Bto527_speed[ , (as.Date(names(NB_Bto527_speed)) %in% new_dates)]

SB_527toB_tt[,-1] =  SB_527toB_tt[,-1] / 3600 
SB_527toB_speed = (mean(SB_527toB$`Avg. Speed`* (SB_527toB$`Avg. TTS`/3600))) /SB_527toB_tt[,-1] 
SB_527toB_speed[SB_527toB_speed < 0] <- NA 
SB_527toB_speed <-SB_527toB_speed[ , (as.Date(names(SB_527toB_speed)) %in% new_dates)] 

#Add back in the time column in the appropriate format
library(chron)
NB_BtoR_speed = cbind(Time = chron(times = as.character(NB_BtoR_tt$Time, "%H:%M:%S")), NB_BtoR_speed)
NB_Bto522_speed = cbind(Time = chron(times = as.character(NB_Bto522_tt$Time, "%H:%M:%S")), NB_Bto522_speed)
SB_RtoB_speed = cbind(Time =chron(times = as.character(SB_RtoB_tt$Time, "%H:%M:%S")), SB_RtoB_speed)
SB_522toB_speed = cbind(Time = chron(times = as.character(SB_522toB_tt$Time, "%H:%M:%S")), SB_522toB_speed)
NB_148to522_speed = cbind(Time = chron(times = as.character(NB_148to522_tt$Time, "%H:%M:%S")), NB_148to522_speed)
SB_522to148_speed = cbind(Time = chron(times = as.character(SB_522to148_tt$Time, "%H:%M:%S")), SB_522to148_speed)
NB_Bto527_speed = cbind(Time =chron(times = as.character(NB_Bto527_tt$Time, "%H:%M:%S")), NB_Bto527_speed)
SB_527toB_speed = cbind(Time = chron(times = as.character(SB_527toB_tt$Time, "%H:%M:%S")), SB_527toB_speed)

library(tidyr)
library(dplyr)

#Match highway segment speed to volume data (averaged for Oct, Nov, Dec 2019, weekends and holidays omitted) 
NB_NE53rd_vol = volume_data  %>% filter(Mileage == 15.63, Date %in% new_dates) %>% select(Date, Time, T_Volume) %>% spread( Date, T_Volume)
NB_NE53rd = data.frame(Time=NB_NE53rd_vol[,1], Average_Vol=rowMeans(NB_NE53rd_vol[,-1]), Average_Speed = rowMeans(NB_BtoR_speed[,-1], na.rm = TRUE), Location ='NE53rd') 

NB_NE100th_vol = volume_data %>% filter(Mileage == 18.70, Date %in% new_dates) %>% select(Date, Time, T_Volume) %>% spread( Date, T_Volume)
NB_NE100th = data.frame(Time=NB_NE100th_vol[,1], Average_Vol=rowMeans(NB_NE100th_vol[,-1]), Average_Speed = rowMeans(NB_Bto522_speed[,-1], na.rm = TRUE),  Location ='NE100th')

NB_SR522_vol = volume_data %>% filter(Mileage == 24.39, Date %in% new_dates) %>% select(Date, Time, T_Volume) %>% spread( Date, T_Volume)
NB_SR522 = data.frame(Time=NB_SR522_vol[,1], Average_Vol=rowMeans(NB_SR522_vol[,-1]), Average_Speed = rowMeans(NB_148to522_speed[,-1], na.rm = TRUE), Location ='SR522')

NB_SR527_vol = volume_data %>% filter(Mileage == 27.44, Date %in% new_dates, Direction == "North") %>% select(Date, Time, T_Volume) %>% spread( Date, T_Volume)
NB_SR527 = data.frame(Time=NB_SR527_vol[,1], Average_Vol=rowMeans(NB_SR527_vol[,-1]), Average_Speed = rowMeans(NB_Bto527_speed[,-1], na.rm = TRUE), Location ='SR527')

#Southbound Direction
SB_NE53rd_vol = volume_data %>% filter(Mileage == 16.67, Date %in% new_dates) %>% select(Date, Time, T_Volume) %>% spread( Date, T_Volume)
SB_NE53rd = data.frame(Time=SB_NE53rd_vol[,1], Average_Vol=rowMeans(SB_NE53rd_vol[,-1]), Average_Speed = rowMeans(SB_RtoB_speed[,-1], na.rm = TRUE), Location ='NE53rd')

SB_NE100th_vol = volume_data %>% filter(Mileage == 19.21, Date %in% new_dates) %>% select(Date, Time, T_Volume) %>% spread( Date, T_Volume)
SB_NE100th = data.frame(Time=SB_NE100th_vol[,1], Average_Vol=rowMeans(SB_NE100th_vol[,-1]), Average_Speed =rowMeans(SB_522toB_speed[,-1], na.rm = TRUE), Location ='NE100th' )

SB_SR522_vol = volume_data %>% filter(Mileage == 23.51, Date %in% new_dates) %>% select(Date, Time, T_Volume) %>% spread( Date, T_Volume)
SB_SR522 = data.frame(Time=SB_SR522_vol[,1], Average_Vol=rowMeans(SB_SR522_vol[,-1]), Average_Speed =rowMeans(SB_522to148_speed[,-1], na.rm = TRUE), Location ='SR522' )

SB_SR527_vol = volume_data %>% filter(Mileage == 27.44, Date %in% new_dates, Direction == "South") %>% select(Date, Time, T_Volume) %>% spread( Date, T_Volume)
SB_SR527 = data.frame(Time=SB_SR527_vol[,1], Average_Vol=rowMeans(SB_SR527_vol[,-1]), Average_Speed = rowMeans(SB_527toB_speed[,-1], na.rm=TRUE), Location ='SR527')

#combine rows from all the milepost data into one dataframe
SouthB = rbind(SB_SR527,SB_SR522, SB_NE100th, SB_NE53rd)
NorthB = rbind(NB_NE53rd, NB_NE100th, NB_SR522, NB_SR527)

```

```{r plot_speed_by_location, message= FALSE,warning= FALSE}
library(ggplot2)

#model average speed at each milepost across the day for Southbound direction. Weekends and holidays are excluded
ggplot(SouthB, aes(Time, Location, fill= Average_Speed)) + geom_tile() +  scale_x_time( name= "Time of Day", limits = c('.25','.85'), breaks = c( '.25', '.33','.416','.5', '.583','.66', '.75', '.83'),  labels = c( "6am", "8am", "10am", "12pm","2pm", "4pm", "6pm", '8pm')) + xlab("Time of Day") + ylab("Location") + scale_fill_gradient2(low = "red", mid = "yellow", high = "chartreuse3", midpoint = 50, space = "Lab", guide = "colourbar", aesthetics = "fill", limits = c(40,60)) + ggtitle("Southbound Toll Lane Speeds")+ labs(fill="Average Speed")

#model average speed at each milepost across the day for Northbound direction. 
ggplot(NorthB, aes(Time, Location, fill= Average_Speed)) + geom_tile() +  scale_x_time( name= "Time of Day", limits = c('.25','.85'), breaks = c( '.25', '.33','.416','.5', '.583','.66', '.75', '.83'),  labels = c( "6am", "8am", "10am", "12pm","2pm", "4pm", "6pm", "8pm")) + xlab("Time of Day") + ylab("Location") + scale_fill_gradient2(low = "red", mid = "yellow", high = "chartreuse3", midpoint = 50, space = "Lab", guide = "colourbar", aesthetics = "fill", limits = c(40,60))+ ggtitle("Northbound Toll Lane Speeds") + labs(fill="Average Speed")

```

```{r plot_vol_by_location, message= FALSE,warning= FALSE}
library(ggplot2)

#model volume at each milepost across the day for Southbound direction. Holidays and weekends are currently excluded from the average volume calculation.
ggplot(SouthB, aes(Time, Location, fill= Average_Vol)) + geom_tile() +  scale_x_time( name= "Time of Day", limits = c('.25','.85'), breaks = c( '.25', '.33','.416','.5', '.583','.66', '.75', '.83'),  labels = c( "6am", "8am", "10am", "12pm","2pm", "4pm", "6pm", '8pm')) + xlab("Time of Day") + ylab("Location") + scale_fill_gradient2(low = "chartreuse3", mid = "yellow", high = "red", midpoint = 150, space = "Lab", guide = "colourbar", aesthetics = "fill", limits=c(0,300)) + ggtitle("Southbound Toll Lane Volume")+ labs(fill="Average Volume")

#model  volume at each milepost across the day for Northbound direction. Holidays and weekends are currently excluded from the average volume calculation.
ggplot(NorthB, aes(Time, Location, fill= Average_Vol)) + geom_tile() +  scale_x_time( name= "Time of Day", limits = c('.25','.85'), breaks = c( '.25', '.33','.416','.5', '.583','.66', '.75', '.83'),  labels = c( "6am", "8am", "10am", "12pm","2pm", "4pm", "6pm", "8pm")) + xlab("Time of Day") + ylab("Location") + scale_fill_gradient2(low = "chartreuse3", mid = "yellow", high = "red", midpoint = 150, space = "Lab", guide = "colourbar", aesthetics = "fill", limits=c(0,300))+ ggtitle("Northbound Toll Lane Volume") + labs(fill="Average Volume")

```




```{r, read_in_rate_data}

#Read in rates 
NB_NE53rd_rates <- read.csv(file = "Data/Rates_1351.csv") #matches to Bellevue-Rosehill speeds and NE 53rd volumes
#reformat headers to dates 
names(NB_NE53rd_rates) <- gsub("Displayed.Toll.Rate.for.", "", names(NB_NE53rd_rates))
names(NB_NE53rd_rates) <- gsub("\\.", "", names(NB_NE53rd_rates))
names(NB_NE53rd_rates) <- c("TimeX", "Time", as.list(as.character(as.Date(colnames(NB_NE53rd_rates[3:ncol(NB_NE53rd_rates)]), format="%m%d%Y"))))
#reformat TimeX column to be consistent with rest of data
NB_NE53rd_rates$TimeX <- paste(NB_NE53rd_rates$TimeX, ":00", sep='')
NB_NE53rd_rates$TimeX <- as.times(NB_NE53rd_rates$TimeX)
 

NB_NE100th_rates <- read.csv(file = "Data/Rates_1585.csv") #matches to Bellevue-SR 522 speed and NE 100th volumes
names(NB_NE100th_rates) <- gsub("Displayed.Toll.Rate.for.", "", names(NB_NE100th_rates))
names(NB_NE100th_rates) <- gsub("\\.", "", names(NB_NE100th_rates))
names(NB_NE100th_rates) <- c("TimeX", "Time", as.list(as.character(as.Date(colnames(NB_NE100th_rates[3:ncol(NB_NE100th_rates)]), format="%m%d%Y"))))
NB_NE100th_rates$TimeX <- paste(NB_NE100th_rates$TimeX, ":00", sep='')
NB_NE100th_rates$TimeX <- as.times(NB_NE100th_rates$TimeX)


NB_SR522_rates <- read.csv(file = "Data/Rates_1879.csv") #matches NE 148th to SR 522 speed and SR 522 volumes
names(NB_SR522_rates) <- gsub("Displayed.Toll.Rate.for.", "", names(NB_SR522_rates))
names(NB_SR522_rates) <- gsub("\\.", "", names(NB_SR522_rates))
names(NB_SR522_rates) <- c("TimeX", "Time", as.list(as.character(as.Date(colnames(NB_SR522_rates[3:ncol(NB_SR522_rates)]), format="%m%d%Y"))))
NB_SR522_rates$TimeX <- paste(NB_SR522_rates$TimeX, ":00", sep='')
NB_SR522_rates$TimeX <- as.times(NB_SR522_rates$TimeX)


NB_SR527_rates <- read.csv(file = "Data/Rates_2526.csv") #matches Bellevue to SR 527 speed and SR 527 volumes
names(NB_SR527_rates) <- gsub("Displayed.Toll.Rate.for.", "", names(NB_SR527_rates))
names(NB_SR527_rates) <- gsub("\\.", "", names(NB_SR527_rates))
names(NB_SR527_rates) <- c("TimeX", "Time", as.list(as.character(as.Date(colnames(NB_SR527_rates[3:ncol(NB_SR527_rates)]), format="%m%d%Y"))))
NB_SR527_rates$TimeX <- paste(NB_SR527_rates$TimeX, ":00", sep='')
NB_SR527_rates$TimeX <- as.times(NB_SR527_rates$TimeX)


SB_NE53rd_rates <- read.csv(file = "Data/Rates_1926.csv") #matches to Rosehill- Bellevue speeds and NE 53rd volumes
names(SB_NE53rd_rates) <- gsub("Displayed.Toll.Rate.for.", "", names(SB_NE53rd_rates))
names(SB_NE53rd_rates) <- gsub("\\.", "", names(SB_NE53rd_rates))
names(SB_NE53rd_rates) <- c("TimeX", "Time", as.list(as.character(as.Date(colnames(SB_NE53rd_rates[3:ncol(SB_NE53rd_rates)]), format="%m%d%Y"))))
SB_NE53rd_rates$TimeX <- paste(SB_NE53rd_rates$TimeX, ":00", sep='')
SB_NE53rd_rates$TimeX <- as.times(SB_NE53rd_rates$TimeX)


SB_NE100th_rates <- read.csv(file = "Data/Rates_2072.csv") #matches to SR 522 - Bellevue speeds and NE 100th volumes
names(SB_NE100th_rates) <- gsub("Displayed.Toll.Rate.for.", "", names(SB_NE100th_rates))
names(SB_NE100th_rates) <- gsub("\\.", "", names(SB_NE100th_rates))
names(SB_NE100th_rates) <- c("TimeX", "Time", as.list(as.character(as.Date(colnames(SB_NE100th_rates[3:ncol(SB_NE100th_rates)]), format="%m%d%Y"))))
SB_NE100th_rates$TimeX <- paste(SB_NE100th_rates$TimeX, ":00", sep='')
SB_NE100th_rates$TimeX <- as.times(SB_NE100th_rates$TimeX)


SB_SR522_rates <- read.csv(file = "Data/Rates_2612.csv") #matches to SR 522 -148th speeds and SR 522 volumes
names(SB_SR522_rates) <- gsub("Displayed.Toll.Rate.for.", "", names(SB_SR522_rates))
names(SB_SR522_rates) <- gsub("\\.", "", names(SB_SR522_rates))
names(SB_SR522_rates) <- c("TimeX", "Time", as.list(as.character(as.Date(colnames(SB_SR522_rates[3:ncol(SB_SR522_rates)]), format="%m%d%Y"))))
SB_SR522_rates$TimeX <- paste(SB_SR522_rates$TimeX, ":00", sep='')
SB_SR522_rates$TimeX <- as.times(SB_SR522_rates$TimeX)


SB_SR527_rates <- read.csv(file = "Data/Rates_2782.csv") #matches to SR 527 -Bellevue speeds and SR 527 volumes
names(SB_SR527_rates) <- gsub("Displayed.Toll.Rate.for.", "", names(SB_SR527_rates))
names(SB_SR527_rates) <- gsub("\\.", "", names(SB_SR527_rates))
names(SB_SR527_rates) <- c("TimeX", "Time", as.list(as.character(as.Date(colnames(SB_SR527_rates[3:ncol(SB_SR527_rates)]), format="%m%d%Y"))))
SB_SR527_rates$TimeX <- paste(SB_SR527_rates$TimeX, ":00", sep='')
SB_SR527_rates$TimeX <- as.times(SB_SR527_rates$TimeX)

```



```{r, match_rate_with_volume}
Temp_vol_data <- cbind(vol_data)
colnames(Temp_vol_data) <-c('Date', 'Day_of_Week', 'Time','T_Volume', 'G_Volume','Direction','Mileage')
Temp_vol_data$Date <- as.Date(Temp_vol_data$Date, format='%Y-%m-%d') 

#Break down the data to match with the rate sheets
N_Temp_vol_data <-data.frame(Temp_vol_data[Temp_vol_data$Direction=="North",])
N53_Temp_vol_data <- data.frame(N_Temp_vol_data[N_Temp_vol_data$Mileage==15.63,])
N100_Temp_vol_data <- data.frame(N_Temp_vol_data[N_Temp_vol_data$Mileage==18.7,])
N522_Temp_vol_data <- data.frame(N_Temp_vol_data[N_Temp_vol_data$Mileage==24.39,])
N527_Temp_vol_data <- data.frame(N_Temp_vol_data[N_Temp_vol_data$Mileage==27.44,])

S_Temp_vol_data <- data.frame(Temp_vol_data[Temp_vol_data$Direction=="South",])
S53_Temp_vol_data <- data.frame(S_Temp_vol_data[S_Temp_vol_data$Mileage==16.67,])
S100_Temp_vol_data <- data.frame(S_Temp_vol_data[S_Temp_vol_data$Mileage==19.21,])
S522_Temp_vol_data <- data.frame(S_Temp_vol_data[S_Temp_vol_data$Mileage==23.51,])
S527_Temp_vol_data <- data.frame(S_Temp_vol_data[S_Temp_vol_data$Mileage==27.44,])

vol_data_list <- list(N53_Temp_vol_data, N100_Temp_vol_data, N522_Temp_vol_data, N527_Temp_vol_data,S53_Temp_vol_data, S100_Temp_vol_data, S522_Temp_vol_data, S527_Temp_vol_data)

rate_data_list <- list(NB_NE53rd_rates, NB_NE100th_rates, NB_SR522_rates,NB_SR527_rates, SB_NE53rd_rates,SB_NE100th_rates, SB_SR522_rates, SB_SR527_rates)

#resulting dataframe
vol_rates_data <- data.frame()

#run through these lists to match rate data with correct location, date, and time
library(dplyr)
k=1
while(k <= 8){
  temp_rate <- rate_data_list[[k]]
  temp_vol <- vol_data_list[[k]]
  tolls <- data.frame() 
  i=0
  while(i <= (NROW(temp_vol)/288)-1) {
      x <- ((i*288))
      if (i == 0)
        x=1
      temp <- data.frame(temp_rate[,colnames(temp_rate)==(as.character(temp_vol$Date[x]))])
      tolls <- rbind(tolls, temp)   
      i=i+1  
  }

  colnames(tolls) <- c("Toll")
  temp_vol <- cbind(temp_vol, tolls)
  
  if (k==1)
    vol_rates_data <- temp_vol
  else
    vol_rates_data <- rbind(vol_rates_data, temp_vol)
  
  k=k+1

}


#clean up rate values
vol_rates_data$Toll <- as.character(vol_rates_data$Toll)
vol_rates_data$Toll[vol_rates_data$Toll == "OPEN"] <- '0'
vol_rates_data$Toll[vol_rates_data$Toll =="CLOSED"] <- '0'
vol_rates_data$Toll[vol_rates_data$Toll =="FREE"] <- "0"
vol_rates_data$Toll[vol_rates_data$Toll =="HOV ONLY"] <- "0"
vol_rates_data$Toll <-as.numeric(vol_rates_data$Toll)

```

```{r another_processing_chunk}
#get data for when toll > 0
library(dplyr)
vrd <- vol_rates_data %>% filter(Toll != 0)


#Prepare speed data to be joined with volume and rates
s1 = NB_BtoR_speed %>% gather(Date, Speed, -Time) %>% add_column(Location = 'NE53rd', Mileage = 15.63, Direction = as.factor("North")) %>%
mutate(Date = as.Date(Date))
s2 = NB_Bto522_speed %>% gather(Date, Speed, -Time) %>% add_column(Location = 'NE100th', Mileage = 18.7, Direction =as.factor("North")) %>%
mutate(Date = as.Date(Date))
s3 = SB_RtoB_speed %>% gather(Date, Speed, -Time) %>% add_column(Location = 'NE53rd', Mileage = 16.67, Direction = as.factor("South")) %>%
mutate(Date = as.Date(Date))
s4 = SB_522toB_speed %>% gather(Date, Speed, -Time) %>% add_column(Location = 'NE100th', Mileage = 19.21, Direction = as.factor("South")) %>%
mutate(Date = as.Date(Date))
s5 = NB_148to522_speed %>% gather(Date, Speed, -Time) %>% add_column(Location = 'SR522', Mileage = 24.39, Direction = as.factor("North")) %>%
mutate(Date = as.Date(Date))
s6 = SB_522to148_speed %>% gather(Date, Speed, -Time) %>% add_column(Location = 'SR522', Mileage = 23.51, Direction =as.factor("South")) %>%
mutate(Date = as.Date(Date))
s7 = NB_Bto527_speed %>% gather(Date, Speed, -Time) %>% add_column(Location = 'SR527', Mileage = 27.44, Direction = as.factor("North")) %>%
mutate(Date = as.Date(Date))
s8 = SB_527toB_speed %>% gather(Date, Speed, -Time) %>% add_column(Location = 'SR527', Mileage = 27.44, Direction = as.factor("South")) %>%
mutate(Date = as.Date(Date))

nspeed = rbind(s1,s2,s5,s7)
sspeed = rbind(s3,s4,s6,s8)
#join on  mileage, time, and date
nres = inner_join(nspeed, vrd, by = c("Date", "Time", "Mileage"))
sres = inner_join(sspeed, vrd, by = c("Date", "Time", "Mileage")) 
sres = sres[sres$Time >= "06:00:00" & sres$Time <= "10:00:00",] #Filter peak times from 6AM to 10AM
nres = nres[nres$Time >= "15:00:00" & nres$Time <= "19:00:00",] #Filter peak times from 3PM to 7PM
res=rbind(nres,sres)
```

```{r plot_speed_vol_rate, warning= FALSE, message= FALSE}
library(ggplot2)

#nvrd = vrd[vrd$Direction =="North",]
#nvrd = nvrd[nvrd$Time >= "15:00:00" & nvrd$Time <= "19:00:00",] #Filter peak times from 3PM to 7PM
#svrd = vrd[vrd$Direction =="South",]
#svrd = svrd[svrd$Time >= "15:00:00" & svrd$Time <= "19:00:00",] #Filter peak times from 3PM to 7PM
#plot rate,  time of day for times when a toll is being charged.  Weekends and holidays excluded.
#plot2 = ggplot(svrd, aes(Toll, Time)) + geom_point()+ xlab("Toll Rate ($)") + ylab("Time of Day") + ggtitle("Time of Day and Toll Rate") +  scale_y_time( name= "Time of Day", limits = c('.25','.85'), breaks = c( '.25', '.33','.416','.5', '.583','.66', '.75', '.83'),  labels = c( "6am", "8am", "10am", "12pm","2pm", "4pm", "6pm", "8pm")) 
#plot rate, toll lane volume for times when a toll is being charged.  Weekends and holidays excluded.
#plot1 = ggplot(svrd, aes(Toll, T_Volume)) + geom_point()+ xlab("Toll Rate ($)") + ylab("Toll Lane Volume") + ggtitle("Toll Lane Volume and Toll Rate") 


#plot speed distribution for each toll rate, Oct - Dec, filtered for peak times and no weekends of holidays
#install.packages("ggridges")
library(ggplot2)
library(ggridges)
library(dplyr)    
ggplot( filter(nres, Toll %% 1 == 0),  aes(x = Speed, y = as.factor(Toll))) + geom_density_ridges_gradient(aes(fill = ..x..)) + ylab("Toll Rate($)") + xlab("Speed(mph)") + ggtitle("Northbound Speed Distribution by Toll Rate") +  scale_fill_gradientn(colours= c("red", "yellow", "chartreuse3"),name = "Speed", values = (c(0, .6,.7,.85,1)))

ggplot( filter(sres, Toll %% 1 == 0),  aes(x = Speed, y = as.factor(Toll))) + geom_density_ridges_gradient(aes(fill = ..x..)) + ylab("Toll Rate ($)") + xlab("Speed(mph)") + ggtitle("Southbound Speed Distribution by Toll Rate")  +  scale_fill_gradientn(colours= c("red", "yellow", "chartreuse3"),name = "Speed", values = (c(0, .6,.7,.85,1)))

#Get average speed for each toll rate
n_agg = aggregate(nres, list(Toll_rate = nres$Toll), mean, na.rm=TRUE)
s_agg = aggregate(sres, list(Toll_rate = sres$Toll), mean, na.rm=TRUE)

#test for normality
#hist(n_agg$Speed)
hist(s_agg$Speed)
mean(s_agg$Speed)
#hist(agg$Speed)
#shapiro.test(n_agg$Speed) #The data is normal if the p-value is above 0.05
#shapiro.test(s_agg$Speed) # This one is normal
#shapiro.test(agg$Speed)

#fit a linear model to southboud data and plot
linearMod <- lm(Toll ~ Speed, data=s_agg) 
#print(linearMod)
#summary(linearMod)
plot(Toll ~ Speed, data = s_agg, ylab = "Toll($)", xlab = "Speed(mph)", col = "red", main = "Average Toll Lane Speed by Toll Rate - Southbound", xlim = c(45,60))
abline(coef(linearMod)[1:2], col = "red")
cf <- round(coef(linearMod), 2) # rounded coefficients for better output
eq <- paste0("Toll = ", cf[1], ifelse(sign(cf[2])==1, " + ", " - "), abs(cf[2]), " X Speed")
mtext(eq, 1, line=-2)

#NB data is not normal, so skip linear model and just scatterplot
plot(Toll ~ Speed, data = n_agg, ylab = "Toll($)", xlab = "Speed(mph)", col = "blue", main = "Average Toll Lane Toll Rate by - Northbound", xlim = c(45,60))

```






